### Get cars

GET {{url}}/api/cars
Content-Type: application/json

### Create car

POST {{url}}/api/cars
Content-Type: application/json

{
  "name": "BMW X6",
  "year": 2010,
  "price": 10000,
  "brand": "BMW"
}

### Delete car

DELETE {{url}}/api/cars/6516fc932b482f6bf74527c6
Content-Type: application/json
